drop table if exists post CASCADE;
drop table if exists user CASCADE;

create table post (id bigint generated by default as identity, body varchar(280) not null, visibility boolean not null, parent_id bigint, user_id bigint, primary key (id));
create table user (id bigint generated by default as identity, email varchar(36) not null, name varchar(36) not null, password varchar(36) not null, username varchar(24) not null, primary key (id));
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email);
alter table user add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table post add constraint FK5yhuvatu7cubfxyltetys1c3n foreign key (parent_id) references post;
alter table post add constraint FK72mt33dhhs48hf9gcqrq4fxte foreign key (user_id) references user;